### ISSUE TITLE
Integración con Django (Django integration)

### ISSUE THREAD

**Issue by ma1onso** [epayco/epayco-python#11]
He creado una app **Django** para que cualquier la descargue y ponga a funcionar en poco tiempo ePayco en su proyecto. Pueden ver el código aquí: https://github.com/ma1onso/depayco, para instalarla solo deben hacer `pip install depayco` y seguir las instrucciones que están en el repositorio.

Espero les sea de ayuda.

**Comment by ortegoncarlos** [comment]
Gracias Bro

**Comment by ma1onso** [comment]
> 
> 
> Gracias Bro

Con gusto, estamos para ayudarnos 🤝 .
