### ISSUE TITLE
No such file or directory: 'pyepayco/utils/key_lang.json'

### ISSUE THREAD

**Issue by jfajardo** [epayco/epayco-python#3]
Tengo ese problema, ya agregué ese archivo pero sigue sin funcionar con este ejemplo

`cash_info = {
            "invoice": "1472050778",
            "description": "pay test",
            "value": "20000",
            "tax": "0",
            "tax_base": "0",
            "currency": "COP",
            "type_person": "0",
            "doc_type": "CC",
            "doc_number": "100000",
            "name": "testing",
            "last_name": "PAYCO",
            "email": "test@mailinator.com",
            "cell_phone": "3010000001",
            "end_date": "2017-12-05",
            "ip": "186.116.10.133",
            "url_response": "https://tudominio.com/respuesta.php",
            "url_confirmation": "https://tudominio.com/confirmacion.php",
            "method_confirmation": "GET",

        }

        cash_efecty = objepayco.cash.create('efecty', cash_info)`

`/lib/python3.5/site-packages/pyepayco/client.py", line 44, in setKeys
    file = open('pyepayco/utils/key_lang.json', 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: 'pyepayco/utils/key_lang.json'`

**Comment by andreolaya** [comment]
El error es muy claro, no encuentra el archivo  "key_lang.json" para establecer las claves. Debes verificar la ruta absoluta de tu proyecto, estás son una de las partes que se deben trabajar, te dejo una solución para:

    # settings.py
    from pathlib import Path
    # Base dir
    BASE_DIR = Path(__file__).resolve().parent.parent
    # EPAYCO UTILS
    EPAYCO_KEY_LANG_FILE = str(BASE_DIR.joinpath('epayco/utils/key_lang.json'))
    # example
    # EPAYCO_KEY_LANG_FILE = '/var/www/myapp/virtualenv/myapp/epayco/utils/key_lang.json'

    # client.py
    from django.conf import settings as s
    class Util():
        def setKeys(self, array={}):
            file = open(s.EPAYCO_KEY_LANG_FILE, 'r').read()
            values = json.loads(file)
            aux = {}
            for key, value in array.items():
                if key in values:
                    aux[values[key]] = value
                else:
                    aux[key] = value
            return aux

**Comment by devepayco** [comment]
Hola, @jfajardo @andreolaya este Issue ya fue resuelto. Por favor descargar la librería nuevamente. Le agradecemos amablemente por su reporte.

**Comment by HasmedFara** [comment]
Este error aún está en la versión que se instala con pip. Por otro lado, la documentación del api es bien escueta, he aquí una lista de cosas para mejoras:
- en muchos lados no se sabe cuales son los campos *requeridos ni la lista de opciones que puede tomar un parámetro (al menos a simple vista).
- cuánto es el monto máximo para pagos con tarjeta de crédito? Es una excepción que lanza el api pero no aparece en la documentación. 
- El proceso de tokenización es muy  verboso: Se crea token, se crea cliente y se asocia (hasta aca bien) pero a la hora de hacer el pago con el token, se especifica el token y también el id del cliente (se supone que el token ya está asociado a un cliente.. podría entonces especificar un cliente que no tiene nada que ver con el token?). 
- El reporte de errores no es consistente.. por ejemplo: El pago por tarjeta de crédito lanza un error al superar un monto x (necesito saber cual es para tratarlo), pero la descripción del mismo dice: 'Cliente o token inexistente'. Esto tan simple te puede hacer perder varias horas buscando el error por otro lado.. Después con un poco de debug encuentras otras variables que tienen más información` {data: {'status': 'error', 'description': 'Verifica que los datos enviados seán existentes o correctos.', 'errors': [{'codError': 'E015', 'errorMessage': 'La transacción no se puede iniciar, monto máximo superado'}]}}` 3 variables que dicen cosas diferentes. 
- La lista de los bancos soportados https://secure.payco.co/restpagos/pse/bancos.json devuelve un error 500.

Mi objetivo es apuntar algunas cosas  que se pueden mejorar ya que los desarrolladores padecemos este tipo de impresiones, tienen un producto ganador pero pobremente mantenido.

**Comment by SamuelBonilla** [comment]
I'm getting the same error, any update ?

**Comment by jlcasasg** [comment]
+1

**Comment by emeagenciadigital** [comment]
+1

**Comment by emeagenciadigital** [comment]
Estamos intentando en PRUEBAS el monto de $483,461 y nos da "La transacción no se puede iniciar, monto máximo superado"

**Comment by pruebasepayco** [comment]
Buenas tardes,

Reciban un cordial saludo.

Informamos que el mensaje retornado 'La transacción no se puede iniciar, monto máximo superado' es más de cuestión administrativa que de código, por lo cual los invitamos a realizar las solicitudes con este caso por medio de tickets en el siguiente enlace, donde se podrá dar una información más apropiada sobre los montos permitidos para cada comercio, estos no son estándares, por lo cual algunos tienen más capacidad de cobro que otros:

https://epayco.co/contacto/

Informamos que se escalara esta solicitud al área encargada para que se tenga una información más amplia en cuanto a los montos permitidos.

Muchas gracias.

**Comment by Gerson-epayco** [comment]
Buenas Tardes

Este issue fue resuelto, por favor descargar la última versión del paquete.

Gracias.
