### ISSUE TITLE
pip install epayco-python no funciona

### ISSUE THREAD

**Issue by uncion7** [epayco/epayco-python#5]
Estoy tratando de instalar epayco-python con pip install pero no funciona me dice que esta libreria no se encuentra. Me podrian ayudar?

**Comment by AlonsoEnrique** [comment]
@uncion7 no te va a funcionar porque ellos no subieron este código a https://pypi.org/, debes instarlo así:

`git clone https://github.com/epayco/epayco-python.git`

Y luego

`sudo python3 setup.py install` (dentro de la carpeta del proyecto)

**Comment by devepayco** [comment]
@uncion7 @AlonsoEnrique puede usar el comando pip install pyepayco

**Comment by gustav0** [comment]
@devepayco Efectivamente este comando funciona, pero no instala la versión que está actualmente en master.

No crea la carpeta de utils ni su contenido, no instala la dependencia pycrypto y por último en la versión que se instala falta código que si está acá en el repositorio.

**Comment by Gerson-epayco** [comment]
Buenas tardes,

Pueden usar los comandos para la correcta instalacion.

Install from Packages (Linux), Pyhton = 3.7
```
   $ pip install epaycosdk
```

Install from Packages (Windows)  Pyhton = 3.7
```
   $ pip install epaycosdk-win
```

Saludos
