### ISSUE TITLE
epayco python necesita pagos divididos

### ISSUE THREAD

**Issue by uncion7** [epayco/epayco-python#6]
La libreria de epayco python no contiene el funcionalidad de pagos divididos. Favor incluir los pagos divididos en la libreria epayco python.

**Comment by pruebasepayco** [comment]
ya, tiene la funcionalidad, seria implementando algunas variables como:
 "splitpayment":"true",
"split_app_id":"xxxx",#este es el id del cliente de la app
"split_merchant_id":"xxxxx",#este es el id del cliente con quien se realizara el split
"split_type" : "02",#tipo de split, de cauerdo a la documentacion es 02 por porcentaje 01 valor fijo 
"split_primary_receiver" : "xxxxx", #id del primer recibirdor, por lo general es "split_app_id"
"split_primary_receiver_fee":"10",#comicion del primer recibidor, split_primary_receiver en este caso 10%, para el split_merchant_id sera el 90%.

este es un ejemplo completo:


payment_info = {
  "token_card": token['id'],
  "customer_id": customer_id,
  "doc_type": "CC",
  "doc_number": "1000000", 
  "name": "John",
  "last_name": "Doe",
  "email": "example@email.com",
  "ip": "192.198.2.114",
  "bill": "OR-12345",
  "description": "Test Payment",
  "value": "119000",
  "tax": "19000",
  "tax_base": "100000",
  "currency": "COP",
  "dues": "12",
  "splitpayment":"true",
  "split_app_id":"19520",
  "split_merchant_id":"17511",
  "split_type" : "02",
  "split_primary_receiver" : "19520",
  "split_primary_receiver_fee":"10",
 
}
