### ISSUE TITLE
https://api.secure.payco.co/ STATUS 502

### ISSUE THREAD

**Issue by JuanSeBestia** [epayco/epayco-python#8]
Urgente! todo se me rompe
Será que ePayco cambio la URL de los servicios?

**Comment by JuanSeBestia** [comment]
Ya volvió el servicio

**Comment by jhonmclein** [comment]
que tal como les va, disculpen por hacer esta pregunta pero yo soy nuevo en esto. 
si yo ejecuto el procedimiento como se ve en los ejemplos con una tarjeta de debito si todo esta correctamente si hace el pago o transferencia de dinero?
